blacklist.conf: bd99f9a159b0 arm64: fix undefined reference to 'printk' A special case when CONFIG_PRINTK is not set, which is not needed by bsc#1126040 backport.
suse-commit: b9b07f652e6a35565ed128c60d594f39ae7b8068